# AirportManager/pyproject.toml

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "AirportManager"
version = "0.0.1"

[tool.setuptools]
package-dir = {"" = "src"}